Feature/desktop version
juandapps/portfolio-elon-musk pull request #7
Opened 2022-11-04 18:06 UTC by juandapps

**Learning objectives**

- Understand how to create UIs adaptable to different screen sizes using media queries.
- Understand how to parse a Figma design to create a UI.

**You are welcome to send me a message on Slack or give me Zoom call, I'm available:**
:watch: 9-11 UTC-6
:watch: 14-17 UTC-6

In advance thank you for the feedback :handshake:

2022-11-04 22:24 UTC, Debas-31 requested changes
> ## Hi @juandapps   :wave:
# Status: Required Change :recycle:
Good job so far!
There are some issues that you still need to work on to go to the next project, but you are almost there!
<img src="https://media4.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif"/>


## Highlights 
 - Linters setup :heavy_check_mark:
- GitHub flow :heavy_check_mark: 
- Commit message :heavy_check_mark:
- PR title and summary :heavy_check_mark: 

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 22:24 UTC, Debas-31 commented on css/styles.css
> +    display: none;
- [ ] Make sure the alignments like margin and padding stick to the original design. Please work on this :wrench: 

***Your mobile design***
![Screenshot from 2022-11-05 01-12-36](https://user-images.githubusercontent.com/65129228/200082706-285c81a5-097d-4ea3-96c3-1ddbea869b32.png)

2022-11-04 22:25 UTC, Felix45 approved these changes

2022-11-04 23:14 UTC, juandapps commented on css/styles.css
> +    display: none;
:wave: @Debas-31, can you please check the project using `live-server`, images are probably not rendering because you're opening the project using the `.html` binary.

2022-11-04 23:47 UTC, juandapps commented on css/styles.css
> +
To be honest, I thought we were only required to do two breakpoints :+1:

2022-11-06 03:16 UTC, fherrerao requested changes
# 🦺 🚧 🚥 CHANGES REQUIRED 🚥 🚧 🦺
#
Hi @juandapps, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![So Close Snl GIF by Saturday Night Live](https://user-images.githubusercontent.com/91301423/197784121-950974af-5415-4bf0-871b-ce226a51ace4.gif)
 ## Highlights

✔️  No linter errors.
✔️  You used the correct GitHub-Flow.
✔️  Good README
✔️  Good Commit Messages

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-06 03:16 UTC, fherrerao commented on index.html
> +          <button type="submit" class="card2-btn">See project</button>
- [ ] [OPTIONAL] Please fix the position of the buttons it should be at the bottom of the card 🎲, remember the design should be similar to Figma 🧇.
- [ ] [OPTIONAL] Kindly, also check these buttons in the mobile design. 🅰️

Your design:

![image](https://user-images.githubusercontent.com/91301423/200152159-b4f0c80b-e7ae-4244-ba72-e5c2a3c48d6f.png)

Figma design:

![image](https://user-images.githubusercontent.com/91301423/200152172-55971514-e378-4865-8187-3076f35be986.png)

2022-11-06 03:16 UTC, fherrerao commented on css/styles.css
> +  }
- [ ] Great job with the changes requested by the previous reviewer 💯, but please remove the horizontal scroll bar fixing the width of the screen the original design doesn`t have it 🦺.
- [ ] Please, also fix the margins left and right in the works section, it should stick as much as possible with the Figma design 🦖.

![image](https://user-images.githubusercontent.com/91301423/200151946-84104fa5-8d90-47b7-ac43-56e69efdf1e4.png)

2022-11-06 04:13 UTC, juandapps commented
:wave: @fherrerao

2022-11-06 04:24 UTC, topeogunleye requested changes
Hi @juandapps, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* No linter errors. :heavy_check_mark:
* Followed Github flow :heavy_check_mark:
* Professional README file. :heavy_check_mark:
* PR has a good title and summary :heavy_check_mark:

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- Check my inline comments

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-06 04:24 UTC, topeogunleye commented on css/styles.css
> +    overflow-x: hidden;
- [ ] [OPTIONAL] Rather than using `overflow-x: hidden`. It is best practice to make your page responsive by using the right CSS values because `overflow-x: hidden` will only cut out some parts of your web page.

https://www.loom.com/share/5a302f3747884127a86f13b31f6d6a5d

2022-11-06 04:24 UTC, topeogunleye commented on index.html
> +              Data Dashboard <br />
- [ ] As suggested by the previous reviewer, please make sure that the margin for your works-section is the same as the Figma design.

| Your Design  | Figma Design |
| ------------- | ------------- |
| <img width="386" alt="image" src="https://user-images.githubusercontent.com/52934128/200153962-1ca74552-006c-4547-bb01-fc0f13f5a808.png">  | <img width="300" alt="image" src="https://user-images.githubusercontent.com/52934128/200153904-c103d21f-f7f8-4c75-a8b9-f5d97a2842a2.png"> |

2022-11-06 04:33 UTC, juandapps commented on index.html
> +              Data Dashboard <br />
:wave: @topeogunleye, I did everything on my laptop (13inch) and on my end I see everything working well, now I tested it on my desktop and I see the problem with the buttons in the desktop (computer) which has a resolution of 3000+

2022-11-06 05:51 UTC, topeogunleye approved these changes
### Hi @juandapps, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title :heavy_check_mark:
 
## [Optional] suggestions:
* [ ]  Please check my inline comments.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-06 05:51 UTC, topeogunleye commented on css/styles.css
> +  #works .card2 {
- [ ] [OPTIONAL] I kindly suggest that you use one CSS selector for all your cards to make your CSS dry. Please apply changes to all affected areas in CSS as I'm unable to comment on some of the code

2022-11-07 02:50 UTC, merged